version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: portal-backend-simple
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
      - backend_db:/app/db.sqlite3
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-66+qjm@3f^=5xav_&v!+_iip$=$=9^z6gorjogr4mw-8a%hfrw
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80
      - CORS_ALLOW_ALL_ORIGINS=True
    networks:
      - portal-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portal-frontend-simple
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portal-network
    restart: unless-stopped

volumes:
  backend_db:

networks:
  portal-network:
    driver: bridge