version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: portal-backend
    ports:
      - "8000:8000"
    volumes:
      - media_files:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-66+qjm@3f^=5xav_&v!+_iip$=$=9^z6gorjogr4mw-8a%hfrw
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80
      - CORS_ALLOW_ALL_ORIGINS=True
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: portal-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend-simple.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  media_files: