# STACK FINAL PARA PORTAINER - PUERTOS 9090 y 8090
# Copia y pega este código en Portainer → Stacks → Web Editor

version: '3.8'

services:
  backend:
    image: python:3.11-slim
    container_name: portal-empleados-backend
    working_dir: /app
    command: >
      bash -c "
      apt-get update && apt-get install -y gcc git &&
      pip install --upgrade pip &&
      pip install Django==5.1.0 djangorestframework==3.15.2 djangorestframework-simplejwt==5.3.0 django-cors-headers==4.3.1 Pillow==10.0.0 &&
      git clone https://github.com/jv-maroto/Portal-Employes.git /tmp/repo &&
      cp -r /tmp/repo/backend/* . &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "9090:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-66+qjm@3f^=5xav_&v!+_iip$=$=9^z6gorjogr4mw-8a%hfrw
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8090
      - CORS_ALLOW_ALL_ORIGINS=True
    volumes:
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: portal-empleados-frontend
    ports:
      - "8090:80"
    command: >
      sh -c "
      echo 'server {
          listen 80;
          location / {
              return 200 \"<!DOCTYPE html><html><head><title>Portal Empleados</title><style>body{font-family:Arial;margin:50px;background:#f5f5f5}.container{background:white;padding:30px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}h1{color:#2c3e50}.link{display:inline-block;margin:10px;padding:15px 25px;background:#3498db;color:white;text-decoration:none;border-radius:5px}.link:hover{background:#2980b9}</style></head><body><div class=container><h1>🏢 Portal Empleados</h1><p>✅ Sistema funcionando correctamente</p><a href=/admin/ class=link>🔧 Django Admin</a><a href=/api/ class=link>📡 API Backend</a><p><strong>Configuración de Puertos:</strong></p><p>🔧 Backend Django: Puerto 9090</p><p>🌐 Frontend Nginx: Puerto 8090</p><p><strong>URLs de acceso:</strong></p><p>Frontend: http://tu-servidor:8090</p><p>Admin: http://tu-servidor:8090/admin/</p><p>API: http://tu-servidor:8090/api/</p></div></body></html>\";
              add_header Content-Type text/html;
          }
          location /admin/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
          }
          location /api/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
          }
          location /static/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
          }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_media:
  backend_static: