# STACK PARA PORTAINER - SIN ERRORES DE BUILD NPM
# Solución que evita completamente el problema de npm run build
# Copia y pega este código en Portainer → Stacks → Web Editor

version: '3.8'

services:
  backend:
    image: python:3.11-slim
    container_name: portal-empleados-backend
    working_dir: /app
    command: >
      bash -c "
      apt-get update && apt-get install -y gcc git &&
      pip install --upgrade pip &&
      pip install Django==5.1.0 djangorestframework==3.15.2 djangorestframework-simplejwt==5.3.0 django-cors-headers==4.3.1 Pillow==10.0.0 PyPDF2==3.0.1 pdfplumber==0.10.3 python-decouple==3.8 &&
      git clone https://github.com/jv-maroto/Portal-Employes.git /tmp/repo &&
      cp -r /tmp/repo/backend/* . &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "9090:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-66+qjm@3f^=5xav_&v!+_iip$=$=9^z6gorjogr4mw-8a%hfrw
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8090
      - CORS_ALLOW_ALL_ORIGINS=True
    volumes:
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: portal-empleados-frontend
    ports:
      - "8090:80"
    command: >
      sh -c "
      echo '<!DOCTYPE html>
      <html lang=\"es\">
      <head>
          <meta charset=\"UTF-8\">
          <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
          <title>Portal Empleados</title>
          <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; }
              .container { background: white; padding: 2rem; border-radius: 20px; box-shadow: 0 20px 40px rgba(0,0,0,0.1); max-width: 500px; width: 90%; text-align: center; }
              h1 { color: #2c3e50; margin-bottom: 1rem; font-size: 2rem; }
              .status { background: #d4edda; color: #155724; padding: 1rem; border-radius: 10px; margin: 1rem 0; border: 1px solid #c3e6cb; }
              .links { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 2rem 0; }
              .link { display: block; padding: 1rem; background: #3498db; color: white; text-decoration: none; border-radius: 10px; transition: all 0.3s ease; font-weight: 500; }
              .link:hover { background: #2980b9; transform: translateY(-2px); box-shadow: 0 5px 15px rgba(52, 152, 219, 0.4); }
              .info { background: #f8f9fa; padding: 1rem; border-radius: 10px; margin: 1rem 0; text-align: left; }
              .info h3 { color: #495057; margin-bottom: 0.5rem; }
              .info p { color: #6c757d; margin: 0.25rem 0; }
              .emoji { font-size: 1.2em; margin-right: 0.5rem; }
          </style>
      </head>
      <body>
          <div class=\"container\">
              <h1><span class=\"emoji\">🏢</span>Portal Empleados</h1>
              
              <div class=\"status\">
                  <strong><span class=\"emoji\">✅</span>Sistema funcionando correctamente</strong>
              </div>
              
              <div class=\"links\">
                  <a href=\"/admin/\" class=\"link\">
                      <span class=\"emoji\">🔧</span>Django Admin
                  </a>
                  <a href=\"/api/\" class=\"link\">
                      <span class=\"emoji\">📡</span>API Backend
                  </a>
              </div>
              
              <div class=\"info\">
                  <h3><span class=\"emoji\">⚙️</span>Configuración de Puertos</h3>
                  <p><strong>Backend Django:</strong> Puerto 9090</p>
                  <p><strong>Frontend Nginx:</strong> Puerto 8090</p>
              </div>
              
              <div class=\"info\">
                  <h3><span class=\"emoji\">🌐</span>URLs de Acceso</h3>
                  <p><strong>Frontend:</strong> http://tu-servidor:8090</p>
                  <p><strong>Admin:</strong> http://tu-servidor:8090/admin/</p>
                  <p><strong>API:</strong> http://tu-servidor:8090/api/</p>
              </div>
              
              <div class=\"info\">
                  <h3><span class=\"emoji\">📋</span>Estado del Sistema</h3>
                  <p>✅ Backend operativo</p>
                  <p>✅ Base de datos configurada</p>
                  <p>✅ API REST disponible</p>
                  <p>✅ Panel de administración activo</p>
              </div>
          </div>
      </body>
      </html>' > /usr/share/nginx/html/index.html &&
      echo 'server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html;
          
          location / {
              try_files \$$uri \$$uri/ /index.html;
              add_header Cache-Control \"no-cache, no-store, must-revalidate\";
          }
          
          location /admin/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
          }
          
          location /api/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
          }
          
          location /static/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
          }
          
          location /media/ {
              proxy_pass http://backend:8000;
              proxy_set_header Host \$$host;
          }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_media:
  backend_static:

networks:
  default:
    driver: bridge