# Generated by Django 5.2.4 on 2026-03-09 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('IT', 'Informática'), ('FIN', 'Finanzas')], default='RRHH', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('download_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 dígitos seguidos de una letra válida.', regex='^\\d{8}[A-HJ-NP-TV-Z]$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'year'], name='idx_pdffile_user_year')],
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('motivo', models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Días Libres', 'Días Libres'), ('Permisos', 'Permisos'), ('Enfermedad', 'Enfermedad')], max_length=50)),
                ('inicio', models.DateField(db_index=True)),
                ('fin', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('file', models.FileField(blank=True, null=True, upload_to='vacaciones/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'year'], name='idx_vacacion_user_year')],
            },
        ),
    ]
