# Generated by Django 5.0 on 2024-08-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pdfupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfupload',
            options={'verbose_name': 'Subir Nómina', 'verbose_name_plural': 'Subir Nóminas'},
        ),
    ]
