# Generated by Django 5.0 on 2024-08-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_pdfupload_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFUpload',
        ),
    ]
