# Generated by Django 5.0 on 2024-08-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_nomina_user'),
        ('base', '0009_delete_pdfupload'),
    ]

    operations = [
    ]
