# Generated by Django 5.0 on 2024-09-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_pdffile_dni_alter_pdffile_month_alter_pdffile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='dni',
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
