# Generated by Django 5.0 on 2024-09-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_pdffile_dni_alter_pdffile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Días Libres', 'Días Libres'), ('Permiso', 'Permiso')], max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
