# Generated by Django 5.0 on 2024-10-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='pdf_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pdffile'),
        ),
    ]
