# Generated by Django 5.0.3 on 2025-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_vacacion_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacacion',
            name='motivo',
            field=models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Días Libres', 'Días Libres'), ('Permisos', 'Permisos')], max_length=255),
        ),
    ]
