# Generated by Django 5.0.3 on 2025-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_vacacion_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(choices=[('Políticas', 'Políticas'), ('Eventos', 'Eventos'), ('Noticia', 'Noticia'), ('RRHH', 'Recursos Humanos'), ('Sistemas IT', 'Sistemas IT'), ('Marketing', 'Marketing')], default='Noticia', max_length=50),
        ),
    ]
