# Generated by Django 5.0.3 on 2025-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_post_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='download_only',
            field=models.BooleanField(default=False),
        ),
    ]
