# Generated by Django 5.0.3 on 2025-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_post_download_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacacion',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='vacacion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vacaciones/'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='month',
            field=models.CharField(default='Sin mes', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacacion',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('IT', 'Informática'), ('FIN', 'Finanzas')], default='RRHH', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacacion',
            name='motivo',
            field=models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Días Libres', 'Días Libres'), ('Permisos', 'Permisos'), ('Enfermedad', 'Enfermedad')], max_length=50),
        ),
    ]
